apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-api-depl
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-api
  template:
    metadata:
      labels:
        app: express-api
    spec:
      containers:
        - name: express-api
          image: asd2321s2/express-api:{{ GITHUB_SHA }}
          imagePullPolicy: Always #  Avoid pod still using the old image because it is cached
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
