apiVersion: v1
kind: Service
metadata:
  name: express-api-srv
  namespace: default
spec:
  selector:
    app: express-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
