apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: express-mongo-statefulset
  namespace: express-dev
spec:
  serviceName: express-mongo-srv
  replicas: 3
  selector:
    matchLabels:
      app: express-mongo
  template:
    metadata:
      labels:
        app: express-mongo
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: express-mongo
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: express-mongo-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: express-mongo-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
          command: ["/bin/bash", "-c"]
          args:
            - |
              mongod --replSet rs0 --bind_ip_all & sleep 10
              if [[ "$(hostname)" == "express-mongo-statefulset-0" ]]; then
                mongo --eval "
                rs.initiate({
                  _id: 'rs0',
                  members: [
                    { _id: 0, host: 'express-mongo-statefulset-0.express-mongo-srv.default.svc.cluster.local:27017' },
                    { _id: 1, host: 'express-mongo-statefulset-1.express-mongo-srv.default.svc.cluster.local:27017' },
                    { _id: 2, host: 'express-mongo-statefulset-2.express-mongo-srv.default.svc.cluster.local:27017' }
                  ]
                })"
              fi
              tail -f /dev/null
          # livenessProbe:
          #   exec:
          #     command:
          #       - mongo
          #       - --eval
          #       - "db.adminCommand('ping')"
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          # readinessProbe:
          #   exec:
          #     command:
          #       - mongo
          #       - --eval
          #       - "rs.status()"
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
