apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-api-depl
  namespace: express-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-api
  template:
    metadata:
      labels:
        app: express-api
    spec:
      containers:
        - name: express-api
          image: asd2321s2/express-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
          # livenessProbe:
          #   httpGet:
          #     path: /v1/docs
          #     port: 3000
          #   initialDelaySeconds: 10
          #   periodSeconds: 5
          # readinessProbe:
          #   httpGet:
          #     path: /v1/docs
          #     port: 3000
          #   initialDelaySeconds: 5
          #   periodSeconds: 5
          env:
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: express-api-secret
                  key: MONGODB_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: express-api-secret
                  key: JWT_SECRET
            - name: SMTP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: express-api-secret
                  key: SMTP_USERNAME
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: express-api-secret
                  key: SMTP_PASSWORD
            - name: JWT_ACCESS_EXPIRATION_MINUTES
              value: "30"
            - name: JWT_REFRESH_EXPIRATION_DAYS
              value: "30"
            - name: JWT_RESET_PASSWORD_EXPIRATION_MINUTES
              value: "10"
            - name: JWT_VERIFY_EMAIL_EXPIRATION_MINUTES
              value: "10"
            - name: SMTP_HOST
              value: "smtp.mailtrap.io"
            - name: SMTP_PORT
              value: "2525"
            - name: EMAIL_FROM
              value: "support@yourapp.com"
