apiVersion: v1
kind: Service
metadata:
  name: express-mongo-srv
  namespace: express-dev
spec:
  clusterIP: None  # Headless Service để StatefulSet có thể truy cập qua DNS cố định
  selector:
    app: express-mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
