apiVersion: v1
kind: Secret
metadata:
  name: express-mongo-secret
  namespace: express-dev
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4=   # Giá trị "admin" được mã hóa base64
  MONGO_INITDB_ROOT_PASSWORD: cGFzc3dvcmQ=  # Giá trị "password1" được mã hóa base64
