apiVersion: v1
kind: Secret
metadata:
  name: express-api-secret
  namespace: express-dev
type: Opaque
data:
  JWT_SECRET: dGhpc2lzYXNhbXBsZXNlY3JldA==
  MONGODB_URL: bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkQGV4cHJlc3MtbW9uZ28tc3RhdGVmdWxzZXQtMC5leHByZXNzLW1vbmdvLXNydi5leHByZXNzLWRldi5zdmMuY2x1c3Rlci5sb2NhbDoyNzAxNyxleHByZXNzLW1vbmdvLXN0YXRlZnVsc2V0LTEuZXhwcmVzcy1tb25nby1zcnYuZXhwcmVzcy1kZXYuc3ZjLmNsdXN0ZXIubG9jYWw6MjcwMTcsZXhwcmVzcy1tb25nby1zdGF0ZWZ1bHNldC0yLmV4cHJlc3MtbW9uZ28tc3J2LmV4cHJlc3MtZGV2LnN2Yy5jbHVzdGVyLmxvY2FsOjI3MDE3L25vZGUtYm9pbGVycGxhdGU/cmVwbGljYVNldD1yczAmYXV0aFNvdXJjZT1hZG1pbg==
  SMTP_USERNAME: Y29ybmFsLW1haWx0cmFw
  SMTP_PASSWORD: YWRtaW5AQUJDRA==

# echo -n "mongodb://admin:password@express-mongo-statefulset-0.express-mongo-srv.express-dev.svc.cluster.local:27017,express-mongo-statefulset-1.express-mongo-srv.express-dev.svc.cluster.local:27017,express-mongo-statefulset-2.express-mongo-srv.express-dev.svc.cluster.local:27017/node-boilerplate?replicaSet=rs0&authSource=admin" | base64

# echo -n "mongodb://admin:password@express-mongo-statefulset-0.express-mongo-srv.express-dev.svc.cluster.local:27017,express-mongo-statefulset-1.express-mongo-srv.express-dev.svc.cluster.local:27017,express-mongo-statefulset-2.express-mongo-srv.express-dev.svc.cluster.local:27017/node-boilerplate?replicaSet=rs0" | base64
