apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-api-depl
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-api
  template:
    metadata:
      labels:
        app: express-api
    spec:
      containers:
        - name: express-api
          image: asd2321s2/express-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
          env:
            - name: MONGODB_URL
              value: "mongodb://admin:password@mongo-service.default.svc.cluster.local:27017"
            - name: JWT_SECRET
              value: "thisisasamplesecret"
            - name: JWT_ACCESS_EXPIRATION_MINUTES
              value: "30"
            - name: JWT_REFRESH_EXPIRATION_DAYS
              value: "30"
            - name: JWT_RESET_PASSWORD_EXPIRATION_MINUTES
              value: "10"
            - name: JWT_VERIFY_EMAIL_EXPIRATION_MINUTES
              value: "10"
            - name: SMTP_HOST
              value: "smtp.mailtrap.io"
            - name: SMTP_PORT
              value: "2525"
            - name: SMTP_USERNAME
              value: "your-mailtrap-username"
            - name: SMTP_PASSWORD
              value: "your-mailtrap-password"
            - name: EMAIL_FROM
              value: "support@yourapp.com"
