apiVersion: v1
kind: Secret
metadata:
  name: express-api-secret
  namespace: default
type: Opaque
data:
  JWT_SECRET: dGhpc2lzYXNhbXBsZXNlY3JldA==
  MONGODB_URL: bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkQGV4cHJlc3MtbW9uZ28tc3J2LmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWw6MjcwMTc=
  SMTP_USERNAME: Y29ybmFsLW1haWx0cmFw
  SMTP_PASSWORD: YWRtaW5AQUJDRA==
