name: Deploy Dev

on:
  push:
    branches: ["develop"]

jobs:
  backend-image:
    uses: ./.github/workflows/job-build-push-image.yml
    with:
      environment: dev
      ref: develop
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  sync-repository:
    uses: ./.github/workflows/job-deploy-be.yml
    needs: backend-image
    with:
      environment: dev
      ref: develop

