name: Job Build & Push Docker Image

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      ref:
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  build:
    name: Build docker image ${{ inputs.environment }}
    environment: ${{ inputs.environment }}
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        run: |
          set -e
          echo "Logging in to Docker Hub"
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          set -e
          IMAGE_NAME=asd2321s2/express-api
          TAG=${{ github.sha }}

          echo "Building Docker image with tag: $TAG"
          docker buildx build \
            --cache-from=type=registry,ref=$IMAGE_NAME:latest \
            --cache-to=type=registry,ref=$IMAGE_NAME:build-cache,mode=max \
            --tag $IMAGE_NAME:$TAG \
            --push .

      - name: Tag and push latest image
        run: |
          set -e
          IMAGE_NAME=asd2321s2/express-api
          TAG=${{ github.sha }}

          echo "Tagging latest image"
          docker tag $IMAGE_NAME:$TAG $IMAGE_NAME:latest || { echo "Tagging failed!"; exit 1; }

          echo "Pushing latest image"
          docker push $IMAGE_NAME:latest || { echo "Push failed!"; exit 1; }

      - name: Tag and push release versions
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          set -e
          IMAGE_NAME=asd2321s2/express-api
          TAG=${GITHUB_REF#refs/tags/}

          if [[ -z "$TAG" ]]; then
            echo "Invalid tag. Exiting..."
            exit 1
          fi

          echo "Tagging release version: $TAG"
          docker tag $IMAGE_NAME:${{ github.sha }} $IMAGE_NAME:$TAG || { echo "Tagging failed!"; exit 1; }

          echo "Pushing release image"
          docker push $IMAGE_NAME:$TAG || { echo "Push failed!"; exit 1; }
